# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(535, 390)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(535, 390))
        MainWindow.setMaximumSize(QtCore.QSize(535, 390))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icônes/SQL.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 518, 350))
        self.layoutWidget.setObjectName("layoutWidget")
        self.TotalLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.TotalLayout.setContentsMargins(0, 0, 0, 0)
        self.TotalLayout.setObjectName("TotalLayout")
        self.LetfLayout = QtWidgets.QFormLayout()
        self.LetfLayout.setObjectName("LetfLayout")
        self.logo = QtWidgets.QLabel(self.layoutWidget)
        self.logo.setObjectName("logo")
        self.LetfLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.logo)
        self.LayoutDB = QtWidgets.QGridLayout()
        self.LayoutDB.setObjectName("LayoutDB")
        self.l_Connectedto = QtWidgets.QLabel(self.layoutWidget)
        self.l_Connectedto.setObjectName("l_Connectedto")
        self.LayoutDB.addWidget(self.l_Connectedto, 0, 0, 1, 1)
        self.pb_EditConnection = QtWidgets.QPushButton(self.layoutWidget)
        self.pb_EditConnection.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pb_EditConnection.setObjectName("pb_EditConnection")
        self.LayoutDB.addWidget(self.pb_EditConnection, 1, 0, 1, 1)
        self.LetfLayout.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.LayoutDB)
        self.pb_Convert = QtWidgets.QPushButton(self.layoutWidget)
        self.pb_Convert.setObjectName("pb_Convert")
        self.LetfLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pb_Convert)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.LetfLayout.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.LetfLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.TotalLayout.addLayout(self.LetfLayout, 0, 0, 1, 1)
        self.RightgridLayout = QtWidgets.QGridLayout()
        self.RightgridLayout.setObjectName("RightgridLayout")
        self.pb_Add = QtWidgets.QPushButton(self.layoutWidget)
        self.pb_Add.setObjectName("pb_Add")
        self.RightgridLayout.addWidget(self.pb_Add, 2, 0, 1, 1)
        self.l_List = QtWidgets.QLabel(self.layoutWidget)
        self.l_List.setObjectName("l_List")
        self.RightgridLayout.addWidget(self.l_List, 0, 0, 1, 2)
        self.pb_Remove = QtWidgets.QPushButton(self.layoutWidget)
        self.pb_Remove.setObjectName("pb_Remove")
        self.RightgridLayout.addWidget(self.pb_Remove, 2, 1, 1, 1)
        self.lw_CSVfiles = QtWidgets.QListWidget(self.layoutWidget)
        self.lw_CSVfiles.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lw_CSVfiles.setObjectName("lw_CSVfiles")
        self.RightgridLayout.addWidget(self.lw_CSVfiles, 1, 0, 1, 2)
        self.TotalLayout.addLayout(self.RightgridLayout, 0, 1, 1, 1)
        self.lw_Validation = QtWidgets.QListWidget(self.layoutWidget)
        self.lw_Validation.setMaximumSize(QtCore.QSize(16777215, 100))
        self.lw_Validation.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lw_Validation.setObjectName("lw_Validation")
        self.TotalLayout.addWidget(self.lw_Validation, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 535, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icônes/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon1)
        self.actionHelp.setObjectName("actionHelp")
        self.menuMenu.addAction(self.actionHelp)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pb_EditConnection, self.pb_Add)
        MainWindow.setTabOrder(self.pb_Add, self.pb_Remove)
        MainWindow.setTabOrder(self.pb_Remove, self.lw_CSVfiles)
        MainWindow.setTabOrder(self.lw_CSVfiles, self.lw_Validation)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Convert CSV to SQL"))
        self.logo.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/logo/CVS_to_JSON_to_SQL.png\"/></p></body></html>"))
        self.l_Connectedto.setText(_translate("MainWindow", "Connecté à "))
        self.pb_EditConnection.setText(_translate("MainWindow", "Connexion"))
        self.pb_Convert.setText(_translate("MainWindow", "Convertir"))
        self.pb_Add.setText(_translate("MainWindow", "Ajouter"))
        self.l_List.setText(_translate("MainWindow", "Liste des fichiers CSV à convertir :"))
        self.pb_Remove.setText(_translate("MainWindow", "Retirer"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionHelp.setShortcut(_translate("MainWindow", "F1"))
import Images_rc
